### ISSUE TITLE
Angular 4 Implementation

### ISSUE THREAD

**Issue by johnpaulmanoza** [OHIF/angular2-cornerstone#1]
how can i make this work in Angular 4.4 ? Thanks

**Comment by karpawar** [comment]
as much i have tired it with angular 2
for angular 4 you might have to make changes in the **cornerstone-element-directive** 
as its the major change here

**Comment by RkReddy88** [comment]
@karpawar  can you please provide the implementation in angular 2.

**Comment by swederik** [comment]
@RkReddy88 this implementation is in angular 2 already...

**Comment by RkReddy88** [comment]
@swederik  I have tried that dint work for me., i was facing issues with the cornerstone
![image](https://user-images.githubusercontent.com/25411057/33778070-1f3c80f8-dc15-11e7-8c90-826459a0db2b.png)

**Comment by RkReddy88** [comment]
@swederik  It will very helpful to me if you can provide me an example.

Thank you
